### ISSUE TITLE
Knight Rider - first pin too dim

### ISSUE THREAD

**Issue by jameskeogh** [andydoro/IMA767_MEDP349_Spring2019#2]
When working on the Knight Rider assignment, I had a brief period where the first pin was significantly dimmer than all other pins. It isn't happening anymore, but I wasn't able to determine what caused it or what solved it. Did this happen to anyone else? Is it code related?

**Comment by rxnaij** [comment]
This happened to me too! You can kind of see it in the beginning of my [documentation video](https://www.youtube.com/watch?v=z9CWO7dfcO8&feature=youtu.be): the red LED all the way to the right is always dimmer than the others. 

It was that way between different programs, and all of the LEDs were connected to power using the same kinds of resistors and jumper wires, so my best guess is that it has something to do with the Arduino pin it's connected to...

**Comment by andydoro** [comment]
which "first pin"? was it a specific digital pin (e.g. pin D2)? D13 has a built-in LED attached to it, so that one might be expected to be dimmer.

I was thinking it could also indicate a short of some sort- make sure not to place the Arduino over anything metal as you could short out the pins doing so. This is another good reason to attach it to a stiff board [like so](https://www.adafruit.com/product/275)
